apiVersion: v1
kind: Service
metadata:
  name: finguard
spec:
  selector:
    app: finguard
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    {{- if .Values.agentgateway.enabled }}
    - name: gateway
      port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
    {{- end }}
